
using Api.Models;

namespace Api;

public class PaycheckService : IPaycheckService
{
    private const int NumberOfPaychecksPerYear = 26;

    protected IEmployeesService EmployeesService { get; }

    public PaycheckService(IEmployeesService employeesService)
    {
        EmployeesService = employeesService;
    }

    public Paycheck Get(int id)
    {
        var paychecks = GetAll();
        var result = paychecks.FirstOrDefault(paycheck => paycheck.Id == id);

        return result;
    }

    public List<Paycheck> GetAll()
    {
        var employees = EmployeesService.GetAll();
        var result = new List<Paycheck>();

        employees.ForEach(employee => result.AddRange(ComputePaychecks(employee)));

        return result;
    }

    public List<Paycheck> GetByEmployeeId(int id)
    {
        var employee = EmployeesService.Get(id);
        var result = ComputePaychecks(employee);

        return result;
    }

    private List<Paycheck> ComputePaychecks(Employee employee)
    {
        if (employee == null)
        {
            return null;
        }

        //employee annual salary
        var totalAmount = employee.Salary;
        //employees have a base cost of $1,000 per month (for benefits)
        totalAmount -= 1000 * 12;
        //each dependent represents an additional $600 cost per month (for benefits)
        totalAmount -= employee.Dependents.Count * 600 * 12;
        //employees that make more than $80,000 per year will incur an additional 2% of their yearly salary in benefits costs
        if (employee.Salary > 80000)
        {
            totalAmount -= employee.Salary * 0.02m;
        }
        //dependents that are over 50 years old will incur an additional $200 per month
        var dependantsOverFifty = employee.Dependents.Count(dependent => (new DateTime((DateTime.Now - dependent.DateOfBirth).Ticks).Year - 1) > 50);

        totalAmount -= dependantsOverFifty * 200 * 12;

        //26 paychecks per year with deductions spread as evenly as possible on each paycheck
        totalAmount /= NumberOfPaychecksPerYear;

        var result = new List<Paycheck>();

        for (var i = 1; i <= NumberOfPaychecksPerYear; i++)
        {
            var week = i * 2;

            result.Add(new Paycheck
            {
                Id = employee.Id * 1000 + week, //computation just for this example, in real application, Id should be generated by Db
                Employee = employee,
                Week = week,
                Year = DateTime.Now.Year,
                TotalAmount = totalAmount
            });
        }

        return result;
    }
}