using Api.BusinessAccessLayer.Dtos.Paycheck;
using Api.Common.Infrastructure;
using Api.DataAccessLayer.Models;
using Microsoft.Extensions.Options;

namespace Api.BusinessAccessLayer.Calculators;

public class PaycheckCalculator(IOptions<PaycheckSettings> paycheckSettings) : IPaycheckCalculator
{
    public readonly PaycheckSettings paycheckSettings = paycheckSettings.Value;

    public List<GetPaycheckDto> ComputePaychecks(Employee employee)
    {
        //employee annual salary
        var totalAmount = employee.Salary;
        //employees have a base cost of $1,000 per month (for benefits)
        totalAmount -= paycheckSettings.EmployeeBaseCost * 12;
        //each dependent represents an additional $600 cost per month (for benefits)
        totalAmount -= employee.Dependents.Count * paycheckSettings.DependentBaseCost * 12;
        //employees that make more than $80,000 per year will incur an additional 2% of their yearly salary in benefits costs
        if (employee.Salary > paycheckSettings.EmployeeBaseCostYearLimit)
        {
            totalAmount -= employee.Salary * paycheckSettings.EmployeeAdditionalCost;
        }
        //dependents that are over 50 years old will incur an additional $200 per month
        var dependantsOverFifty = employee.Dependents.Count(dependent => (new DateTime((DateTime.Now - dependent.DateOfBirth).Ticks).Year - 1) > paycheckSettings.DependentAgeLimit);

        totalAmount -= dependantsOverFifty * paycheckSettings.DependentAdditionalCost * 12;

        //26 paychecks per year with deductions spread as evenly as possible on each paycheck
        totalAmount /= paycheckSettings.NumberOfPaychecksPerYear;

        var result = new List<GetPaycheckDto>();

        for (var i = 1; i <= paycheckSettings.NumberOfPaychecksPerYear; i++)
        {
            var week = i * 2;

            result.Add(new GetPaycheckDto
            {
                Id = employee.Id * 1000 + week, //computation just for this example, in real application, Id should be generated by Db
                EmployeeFirstName = employee.FirstName!,
                EmployeeLastName = employee.LastName!,
                Week = week,
                Year = DateTime.Now.Year,
                TotalAmount = totalAmount
            });
        }

        return result;
    }
}